config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root to: "items#index"
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rooms, only: [:index, :update] do
      resources :messages, only: [:create, :destroy]
    end
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'メンズ' },
    { id: 2, name: 'レディース' },
    { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' },
    { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: 'おもちゃ・ホビー・グッズ' },
    { id: 7, name: '家電・スマホ・カメラ' },
    { id: 8, name: 'スポーツ・レジャー' },
    { id: 9, name: 'ハンドメイド' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :comment, presence: true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '新品・未使用' },
    { id: 2, name: '未使用に近い' },
    { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' },
    { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :item, uniqueness: { scope: :user }
end

app/models/fee.rb
class Fee < ActiveHash::Base
  self.data = [
    { id: 1, name: '着払い(購入者負担)' },
    { id: 2, name: '送料込み(出品者負担)' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :fee
  belongs_to :prefecture
  belongs_to :shipping_day
  belongs_to :user
  has_one :order
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_one :room, dependent: :destroy
  has_many :comments

  with_options presence: true do
    validates :image, :name, :explanation, :category_id, :condition_id, :fee_id, :prefecture_id, :shipping_day_id
  end
  validates :price, numericality: { only_integer: true, greater_than: 299, less_than: 10_000_000 }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "category_id", "condition_id", "fee_id", "price"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_num
    favorites.length
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :message, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :post_code, :prefecture_id, :city, :house_number, :building, :phone_number, :token

  with_options presence: true do
    validates :post_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)" }
    validates :user_id, :item_id, :city, :house_number, :token
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: "is invalid. Only 10 to 11 digits in half-width numbers." }
  end
  validates :prefecture_id, numericality: { other_than: 0, message: "can't be blank" }

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(post_code: post_code, prefecture_id: prefecture_id, city: city, house_number: house_number, 
                  building: building, phone_number: phone_number, order_id: order.id)
  end

  def create_room
    item = Item.find(item_id)
    limit = (item.order.created_at + 14.day).end_of_day
    Room.create(item_id: item_id, limit: limit)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' },
    { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' },
    { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' },
    { id: 7, name: '福島県' },
    { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' },
    { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' },
    { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' },
    { id: 17, name: '石川県' },
    { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' },
    { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' },
    { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' },
    { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' },
    { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' },
    { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' },
    { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :item
  has_many :messages, dependent: :destroy

  validates :limit, presence: true
  validate :restrict_limit

  def restrict_limit
    return unless limit.present? && created_at.present? && limit.to_i > (created_at + 3.week).end_of_day.to_i

    errors.add(:limit, 'はコミュニケーションページの作成された日の3週間後を超えてはいけません')
  end
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '1~2日で発送' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字（6文字以上）での入力が必須です' }
  validates :nickname, presence: true
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は、全角（漢字・ひらがな・カタカナ）での入力が必須です' }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は、全角（漢字・ひらがな・カタカナ）での入力が必須です' }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'は、全角（カタカナ）での入力が必須です' }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'は、全角（カタカナ）での入力が必須です' }
  validates :birthday, presence: true

  has_many :items
  has_many :orders
  has_many :favorites
  has_many :messages
  has_many :comments

  def self.ransackable_attributes(auth_object = nil)
    ["nickname"]
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    super

    UserMailer.with(nickname: params[:user][:nickname], email: params[:user][:email]).welcome_mail.deliver_later
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @favorite_items = @user.favorites.map(&:item)
    @items = @user.items.order('created_at DESC')
    @graph = BuildGraph.new(@items).build_graph
    # BuilGraphは app/services にあります
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>

<%# パンくずリスト %>
<% breadcrumb :user_show %>

<%# ユーザーの詳細 %>
<div class="user-show">
  <div class="user-detail-box">
    <div class="user-show__name">
      <%= @user.nickname %>
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="edit-btn-area">
          <%= link_to "#", class: "edit-btn" do %>
            <%= image_tag "kkrn_icon_henshuu_6.png", width: "15", height: "15" %>
          <% end %>
          <div class="hidden-text", style="display: none;">編集する</div>
        </div>
      <% end %>
    </div>

    <%# 自分の登録情報を見られるのは自分だけ %>
    <% if user_signed_in? && current_user.id == @user.id %>
      <%# 本人自体の情報 %>
      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-user">名前</th>
            <td class="detail-value"><%= @user.last_name %>　<%= @user.first_name %></td>
          </tr>
          <tr>
            <th class="detail-user">フリガナ</th>
            <td class="detail-value"><%= @user.last_name_kana %>　<%= @user.first_name_kana %></td>
          </tr>
          <tr>
            <th class="detail-user">メールアドレス</th>
            <td class="detail-value"><%= @user.email %></td>
          </tr>
          <tr>
            <th class="detail-user">誕生日</th>
            <td class="detail-value"><%= @user.birthday %></td>
          </tr>
        </tbody>
      </table>

      <%# クレジットカード情報 %>
      <div class="user-show__title">登録済みクレジットカード
        <div class="edit-btn-area">
          <%= link_to "#", class: "edit-btn" do %>
            <%= image_tag "kkrn_icon_henshuu_6.png", width: "15", height: "15" %>
          <% end %>
          <div class="hidden-text", style="display: none;">編集する</div>
        </div>
      </div>
      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-user">カード番号</th>
            <td class="detail-value"><%= "####-####-####-0123" %></td>
          </tr>
          <tr>
            <th class="detail-user">有効期限</th>
            <td class="detail-value"><%= "12/24" %></td>
          </tr>
        </tbody>
      </table>

      <%# 住所情報 %>
      <div class="user-show__title" >登録済み住所等
        <div class="edit-btn-area">
          <%= link_to "#", class: "edit-btn" do %>
            <%= image_tag "kkrn_icon_henshuu_6.png", width: "15", height: "15" %>
          <% end %>
          <div class="hidden-text", style="display: none;">編集する</div>
        </div>
      </div>
      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-user">郵便番号</th>
            <td class="detail-value"><%= "123-4567" %></td>
          </tr>
          <tr>
            <th class="detail-user">住所</th>
            <td class="detail-value"><%= "東京都新宿区青山１−１　柳ビル103" %></td>
          </tr>
          <tr>
            <th class="detail-user">電話番号</th>
            <td class="detail-value"><%= "12345678900" %></td>
          </tr>
        </tbody>
      </table>

      <%# お気に入り登録商品 %>
      <div class="user-show__title">お気に入り登録商品</div>
      <% if @favorite_items != [] %>
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-user">商品名</th>
              <th class="detail-value", style='background-color: #eee;'>商品の詳細ページへのリンク</td> 
            </tr>
            <% @favorite_items.each do |item| %>
              <tr>
                <td class="detail-user", style='background-color: white;'><%= item.name %></th>
                <td class="detail-value"><%= link_to nil , item_url(item) %></td> 
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h3 style="font-size: 25px;">お気に入りに登録した商品が存在しません</h3>
      <% end %>

    <% end %>

    <%# 出品履歴のグラフを表示 %>
    <div class="user-detail__graphs">
      <h2 style="font-size: xx-large; font-weight: bold;">出品商品の傾向</h2>
      <h2 style="font-size: x-large; font-weight: 500">総出品数：<%= @items.length %></h2>

      <% if @graph[:frequency] %>
        <div class="category-graph">
          <h2 class="user-show__subtitle">出品頻度</h2>
          <%= line_chart(@graph[:frequency], width: "500px", height: "300px") %>
        </div>
      <% end %>

      <% if @graph[:category] %>
        <div class="category-graph">
          <h2 class="user-show__subtitle">出品カテゴリーの傾向</h2>
          <%= pie_chart(@graph[:category], width: "500px", height: "300px") %>
        </div>
      <% end %>

      <% if !@items.exists? %>
        <h3 style="font-size: 25px;">出品履歴が存在しません</h3>
      <% end %>
    </div>
  </div>
</div>
<%# /ユーザーの詳細 %>

<%# 出品履歴 %>
<div class="item-contents">
  <h2 class="title">過去に出品した商品</h2>

  <ul class="item-lists">
    <% if @items.exists? %>
      <% @items.each_with_index do |item, index| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>

              <% if item.order %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
              <% end %>

            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br><%= item.fee.name %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= item.favorited_num %></span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    <% else %>
      <h3 style="font-size: 25px;">出品履歴が存在しません</h3>
    <% end %>
  </ul>
</div>

<%= render "shared/footer" %>