config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root to: "items#index"
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rooms, only: [:index, :update] do
      resources :messages, only: [:create, :destroy]
    end
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'メンズ' },
    { id: 2, name: 'レディース' },
    { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' },
    { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: 'おもちゃ・ホビー・グッズ' },
    { id: 7, name: '家電・スマホ・カメラ' },
    { id: 8, name: 'スポーツ・レジャー' },
    { id: 9, name: 'ハンドメイド' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :comment, presence: true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '新品・未使用' },
    { id: 2, name: '未使用に近い' },
    { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' },
    { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :item, uniqueness: { scope: :user }
end

app/models/fee.rb
class Fee < ActiveHash::Base
  self.data = [
    { id: 1, name: '着払い(購入者負担)' },
    { id: 2, name: '送料込み(出品者負担)' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :fee
  belongs_to :prefecture
  belongs_to :shipping_day
  belongs_to :user
  has_one :order
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_one :room, dependent: :destroy
  has_many :comments

  with_options presence: true do
    validates :image, :name, :explanation, :category_id, :condition_id, :fee_id, :prefecture_id, :shipping_day_id
  end
  validates :price, numericality: { only_integer: true, greater_than: 299, less_than: 10_000_000 }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "category_id", "condition_id", "fee_id", "price"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def favorited_num
    favorites.length
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :message, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :post_code, :prefecture_id, :city, :house_number, :building, :phone_number, :token

  with_options presence: true do
    validates :post_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: "is invalid. Include hyphen(-)" }
    validates :user_id, :item_id, :city, :house_number, :token
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: "is invalid. Only 10 to 11 digits in half-width numbers." }
  end
  validates :prefecture_id, numericality: { other_than: 0, message: "can't be blank" }

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(post_code: post_code, prefecture_id: prefecture_id, city: city, house_number: house_number, 
                  building: building, phone_number: phone_number, order_id: order.id)
  end

  def create_room
    item = Item.find(item_id)
    limit = (item.order.created_at + 14.day).end_of_day
    Room.create(item_id: item_id, limit: limit)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' },
    { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' },
    { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' },
    { id: 7, name: '福島県' },
    { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' },
    { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' },
    { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' },
    { id: 17, name: '石川県' },
    { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' },
    { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' },
    { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' },
    { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' },
    { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' },
    { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' },
    { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' },
    { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' },
    { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' },
    { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :item
  has_many :messages, dependent: :destroy

  validates :limit, presence: true
  validate :restrict_limit

  def restrict_limit
    return unless limit.present? && created_at.present? && limit.to_i > (created_at + 3.week).end_of_day.to_i

    errors.add(:limit, 'はコミュニケーションページの作成された日の3週間後を超えてはいけません')
  end
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '1~2日で発送' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字（6文字以上）での入力が必須です' }
  validates :nickname, presence: true
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は、全角（漢字・ひらがな・カタカナ）での入力が必須です' }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は、全角（漢字・ひらがな・カタカナ）での入力が必須です' }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'は、全角（カタカナ）での入力が必須です' }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'は、全角（カタカナ）での入力が必須です' }
  validates :birthday, presence: true

  has_many :items
  has_many :orders
  has_many :favorites
  has_many :messages
  has_many :comments

  def self.ransackable_attributes(auth_object = nil)
    ["nickname"]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_data
  before_action :check_limit
  before_action :authenticate_user!
  before_action :move_to_index

  def index
  end

  def update
    if @room.update(room_params)
      redirect_to item_rooms_path(@item.id)
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_data
    @item = Item.find(params[:item_id])
    @room = @item.room
    @messages = Message.where(room_id: @room.id)
    @message = Message.new
  end

  def room_params
    params.require(:room).permit(:limit).merge(item_id: params[:item_id])
  end

  def check_limit
    if Time.now > @room.limit
      @room.destroy
      redirect_to root_path
    end
  end

  def move_to_index
    return if @room && (current_user.id == @item.user.id || current_user.id == @item.order.user.id)

    redirect_to root_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<%= render "shared/second-header"%>

<%# パンくずリスト %>
<% breadcrumb :room %>

<div class="communication-contents">
  <div class="communication-main">
    <h1 class="communication-title">
      コミュニケーションページ
    </h1>

    <%# 翌日ページ削除の注意 %>
    <div class="communication-limit-alert">
      <p>こちらのページは以下の時間に破棄されます</p>
      <span class="communication-limit-datetime"><%= @room.limit.strftime("%Y-%m-%d %H:%M:%S") %></span><br>
      <% if @room.limit.to_i == (@room.created_at + 3.week).end_of_day.to_i %>
        これ以上の延期はできません
      <% else %>
        <div class="communication-limit-extension">
          <p>期間を延長したいときは下のボタンを押してください(延長は1週間のみです)</p>
          <%= form_with model: @room, url: item_room_path(item_id: @item.id, id: @room.id), local: true do |f| %>
            <%= f.hidden_field :limit, value: @room.limit+ 1.week %>
            <%= f.submit "更新" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%# /翌日ページ削除の注意 %>

    <%# 購入内容の表示 %>
    <%= render partial: "orders/item_info", locals: { item: @item } %>
    <%# /購入内容の表示 %>

    <%# コミュニケーション部分 %>
    <h2 class="communications-title">コミュニケーション</h2>
    <div class="communicators">
      <p>S:出品者 <%= link_to @item.user.nickname, user_path(@item.user.id) %> 様</p>
      <p>B:購入者 <%= link_to @item.order.user.nickname, user_path(@item.order.user.id) %> 様</p>
    </div>
    <div class="communications">
      <div class="message-content", id="message-content">
        <% @messages.each do |message| %>
          <div class="message-area">
            <% if message.user.id == @item.user.id %>
              <%# 出品者は「S」 %>
              <div class="message-user">S</div>
            <% else %>
              <%# 購入者は「B」 %>
              <div class="message-user">B</div>
            <% end %>
            <div class="message-text">
              <%= message.message %>
            </div>
            <% if current_user.id == message.user.id %>
              <div class="message-destroy-link">
                <%= link_to "削除", item_room_message_path(item_id: @item.id, room_id: @room.id, id: message.id), data: { turbo_method: :delete } %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%# メッセージ送信部分 %>
      <% if @message.errors.any? %>
        <div class="message-alert">
          <%= @message.errors.full_messages[0] %>
        </div>
      <% end %>
      <div class="communicate-message-input">
        <%= form_with model: [@room, @message], url: item_room_messages_path(item_id: @item.id, room_id: @room.id), local:true do |f| %>
          <%= f.text_field :message, placeholder: "message", class: "communication-message-text" %>
          <%= f.submit "送信", class: "communication-message-submit" %>
        <% end %>
      </div>
      <%# /メッセージ送信部分 %>
    </div>
    <%# /コミュニケーション部分 %>
  </div>
</div>

<%= render "shared/second-footer"%>